/*
	Description :- preprocessor
	Author :- Pranav R Sonawane
*/
/*
	works of preprocessor
	i] comment removel
	ii] extra white spaces removel
	iii] header file inclusion
	iv] micro expanction
*/
 
#include<stdio.h>
#define MAX 100 // MACRO

// entry point function
int main()
{
	int iNo = 10;
	iNo = iNo+ MAX;
	
	printf("Jay Ganesh\n");
	printf("Value of iNo : %d\n",iNo);
	
	return 0;
}

/*
Code which are generated by the preprocessor

# 10 "51_preprocessor.c"
int main()
{
 int iNo = 10;
 iNo = iNo+ 100;

 printf("Jay Ganesh\n");
 printf("Value of iNo : %d\n",iNo);

 return 0;
}

*/