/*
	Description :- include user define header file
	Author :- Pranav R Sonawane
*/

#include "55_marvellous.h"

int main()
{
	struct Demo obj;
	
	printf("Jay Ganesh\n");
	printf("Inside main\n");
	printf("Value of macro is : %d\n",MAX);
	printf("Size of structure is : %d\n",sizeof(obj));
	
	fun();
	
	return 0; 
}

void fun()
{
	printf("inside fun\n");
}

/*
Code which are generated by the preprocessor
 .i file


# 7 "52_main.c" 2
# 1 "53_marvellous.h" 1


# 7 "53_marvellous.h"
void fun();

struct Demo
{
 int iNo;
 int iValue;
 float fValue;
};
# 8 "52_main.c" 2

int main()
{
 struct Demo obj;

 printf("inside main\n");
 printf("Value of macro is : %d\n",101);
 printf("Size of structure is : %d\n",sizeof(obj));

 fun();

 return 0;
}

void fun()
{
 printf("inside fun\n");
}

*/